name: Tests

on:
  push:
    branches:
    - tests
    - main
  

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: xcodebuild -project 'QuilBus/QuilBus.xcodeproj' -scheme 'QuilBus' -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=15.2' clean test
